// Technical Issue With The Keyboard bookmark_border
// Aman likes to play with strings, so his friend Riya decided to send him a mail, containing a sorted string with unique characters. But, due to some technical issue with her keyboard, whenever she presses a key, the corresponding character gets printed multiple times. Now Riya needs your help for removing all the unwanted characters from her string. For example, If aabbbccdef is a sorted string generated by Riya, then you should output the following string as answer abcdef.

// Complete the function getDesiredString(str) that will take the string as parameter and modify it as specified.

// Input Format:

// The first line of input contains an integer T denoting the no of test cases . Then T test cases follow. Each test case contains a string str. 
// Output Format:

// For each test case, print the new string in new lines.
// Constraints:

// 1 <= T <= 10
// 1 <= length of string <= 10^5
// Each string will contain only lower-case English letters.﻿
// Sample Input

// 2
// aabbccdef
// abddddddd
// Sample Output

// abcdef
// abd


class Result {
    // Return the updated string
    static String getDesiredString(String str) {
      // Write your code here
      Stack<Character> st = new Stack<>();
        
        for(char ch:str.toCharArray()){
            if(st.isEmpty()){
                st.add(ch);
            }else{
                if(st.peek() != ch){
                    st.add(ch);
                }
            }
        }
        StringBuilder ans = new StringBuilder();
        while(!st.isEmpty()){
            ans.append(st.peek());
            st.pop();
        }
        return ans.reverse().toString().trim();
    }
  }